spring:
  zipkin:
    base-url: http://zipkin:9411
    service: 
      name: ${spring.application.name}
    sleuth:
      enable: ture
      sampler:
      percentage: 1
  rabbitmq:
    host: rabbitmq
  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

server:
  port： 9015
